server:
  port: 8080

spring:
  application:
    name: expediente-legado
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:siga98}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:siga98_app}
    password: ${DB_PASSWORD:changeme_app}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
